# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images')),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('shutter', models.CharField(blank=True, max_length=10)),
                ('aperture', models.CharField(blank=True, max_length=10)),
                ('iso', models.CharField(blank=True, max_length=10)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
